[build]
  command = "jekyll build --trace"
  publish = "_site"

[[headers]]
for = "/*"

[headers.values]
          Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=15768000"
   X-Content-Type-Options = "nosniff"
          X-Frame-Options = "DENY"
         X-XSS-Protection = "1; mode=block"